name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read


jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
      fail-fast: false
    name: Build - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0  # Shallow clone disabled to improve Sonarcloud analysis
        show-progress: false
        persist-credentials: false

    - name: Install just
      uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --locked --all-extras --dev

    - name: Lint
      run: just lint-ci

    - name: Test
      run: just test
      env:
        OP_TOKEN: ${{ secrets.OP_TOKEN }}  # zizmor: ignore[secrets-outside-env]

    - name: Scan
      if: ${{ matrix.python-version == '3.12' }}
      uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # zizmor: ignore[secrets-outside-env]

    - name: Push scan results to DefectDojo
      if: ${{ matrix.python-version == '3.12' }}
      run: |
        curl -X 'POST' \
        'https://zap.utiligize.com/api/v2/import-scan/' \
        -H 'accept: application/json' \
        -H 'Content-Type: multipart/form-data' \
        -H 'Authorization: ${DOJO_API_KEY}' \
        -F 'minimum_severity=Info' \
        -F 'active=true' \
        -F 'verified=true' \
        -F 'scan_type=SonarQube API Import' \
        -F 'product_name=configator' \
        -F 'engagement_name=SonarCloud API Import' \
        -F 'close_old_findings=false' \
        -F 'close_old_findings_product_scope=false' \
        -F 'push_to_jira=false' \
        -F 'create_finding_groups_for_all_findings=true'
      env:
        DOJO_API_KEY: ${{ secrets.DOJO_API }}  # zizmor: ignore[secrets-outside-env]
